# Generated by Django 4.2.16 on 2025-11-25 15:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FavouriteMovie',
            new_name='FavoriteMovie',
        ),
    ]
